web-accessibility/config/routes.rb
Rails.application.routes.draw do
 root 'capstone#index'

 get '/capstone', to: 'capstone#index'
 get '/capstone/twilio', to: 'capstone#twilio'
 get '/capstone/email', to: 'capstone#email'
 get '/capstone/translate', to: 'capstone#translate'
 get '/capstone/css', to: 'capstone#css'
end

web-accessibility/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

web-accessibility/app/controllers/capstone_controller.rb
class CapstoneController < ApplicationController

def index	
	render "capstone/index"
end	

def twilio
	if params[:q]

		require 'rubygems' # not necessary with ruby 1.9 but included for completeness
		require 'twilio-ruby'

		# put your credentials here
		account_sid = ENV["ACCOUNT_SID"]
		auth_token = ENV["AUTH_TOKEN"]

		# set up a client to talk to the Twilio REST API
		@client = Twilio::REST::Client.new account_sid, auth_token

		message = @client.account.messages.create(:body => params[:q],
			:to => "+15303015894",
			:from => "+15307630890")

		puts message.sid

		@textinformation = params[:q]

		render :twilio
	end
	
end

def email
	render "capstone/email"
end

def translate
	render "capstone/translate"
end

def css
	render "capstone/css"
end

end

web-accessibility/app/helpers/application_helper.rb
module ApplicationHelper
end

web-accessibility/app/helpers/welcome_helper.rb
module WelcomeHelper
end

web-accessibility/app/views/capstone/index.html.erb
<%= javascript_include_tag "application" %> 

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

   <div id="wrapper">

       
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span class="navbar-brand">Web Accessibility</span>
            </div>
				</nav>
		</div>		


<div id="content-wrapper">
	
	<div id="sidebar-wrapper" class="col-md-offset-2">
	
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			
			<ul class="nav navbar-nav side-nav border down relative">
			
				<li>
					<%= link_to "Twilio Demo", capstone_twilio_path, :class => "index-access-hover" %>
				</li>

				<li>
					<%= link_to "Speech-to-Text Email", capstone_email_path, :class => "index-access-hover" %>
				</li>

			<li>
				<%= link_to "Google Translate", capstone_translate_path, :class => "index-access-hover" %>
			</li>

			<li>
				<%= link_to "WAI-ARIA & CSS", capstone_css_path, :class => "index-access-hover" %>
			</li>
	
		</ul>
	</div> <!-- closes sidebar-wrapper -->

<div id="index-content" class="col-md-8 col-offset-2 index-content-down">

	<h1>
		<i class="fa fa-bookmark index-bookmark" aria-hidden="true"> </i>
	 Web Accessibility </h1>
	<hr class="color-tag">

	<p class="index-intro" style="padding-bottom:15px"> 
		This project is dedicated to web accessibility, and how to incorporate more accessibility features into web applications. Well-done web accessibility can be done by creating a balance between web content and your user needs. I’ve included four web applications, showcasing ways to include these features into your own web applications. 
	</p>

	<h4> Google Speech and Twilio App </h4>
	<p style="padding-bottom:15px"> This application combines both Google Speech-to-Text and Twilio APIs. This application takes in audio speech and sends it as a text message to a mobile phone device. <span> Learn more about the Speech to Mobile Text </span>
		<%= link_to "Twilio Demo", capstone_twilio_path, {:class => "index-project-link"} %>. <br>
	</p>

	<h4> Google Speech to Email App </h4>
	<p style="padding-bottom:15px"> This application combines the power of Google Speech-to-Text API with the functionality of composing an email. Instead of typing, you can speak into a computer microphone, and it will do the typing for you. <span> Learn more about the</span>
		<%= link_to "Speech to Email Demo with Google API", capstone_email_path, {:class => "index-project-link"} %>. <br>
	</p>

	<h4> Google Translate for Web Translation </h4>
	<p style="padding-bottom:15px"> This application shows the simplicity of adding a Google Translation plug-in, make your website multilingual friendly and to attract users who speak limited English or non-English speaking. <span> Learn more about creating a </span>
		<%= link_to "Multilingual Site", capstone_translate_path, {:class => "index-project-link"} %>. <br>
	</p>

  <h4> WAI-ARIA and CSS </h4>
	<p style="padding-bottom:15px"> This application shows some WAI-ARIA standards you can apply to your HTML, as well as CSS features you can incorporate into your website to improve accessibility. <span> Learn more about WAI-ARIA & CSS for</span>
		<%= link_to "Accessible Web Design & Content", capstone_css_path, {:class => "index-project-link"} %>.
	</p>

<span tag="index-to-twilio-tag">

	<p class="p-index-right right"> Go to the <%= link_to "Twilio Demo", capstone_twilio_path, {:class => "index-project-link"} %> 
	<!-- </p> -->

	<i class="fa fa-long-arrow-right" aria-hidden="true"> </i>
	</p>

</span>


<div class="further-reading">

<span class="index-further-reading">
	Further Reading
</span> <br>

<span class="index-access-report">
	<strong>
 Introduction to Web Accessibility 
	</strong>
 </span>	<br>

<p>
	When we tend to think of the word diversity,the word is applied to a wide range of people, varying in color, religion, or creed. However, a part of our diverse population that tends to be forgotten about are people with disabilities. 
</p> 

<p>
	In popular tech culture, the word diversity is a topic surrounding white women and people of color (in much fewer amounts). However, people with disabilities are also a component of diversity. 
</p> 

<p>
	In a study of 100 websites, the United Nations commissioned an audit to find out how many websites were accessible for people with disabilities. The results of this study found only 3 of 100 websites met international standards for accessibility. This can only lead us to this conclusion: people with disabilities are largely unable to access the internet.
</p> 

<p>
	We are living in the times of a social media fixation - ranging from popular websites such as Ted Talks, YouTube, Netflix, and more. Most of the these podcasts and videos on popular social media websites are produced without captions or transcripts. 
</p>

<p>
	We can create a more tolerant and inclusive internet culture by striving to create and modify existing websites to become more accessible for people with disabilities.
</p> 

<p>
	This starts by having software development teams learn how to make accessible websites. Most of disabled users have challenges when using keyboards, mouses, and speakers - as an alternative using screen readers are commonly used to experience and interact with websites. 
</p> 

<p>
	One major way to incorporate web accessibility into websites is to learn WAI-ARIA, which stands for “Web Accessibility Initiative - Accessible Rich Internet Applications.” A great resource to learn more about these standards, can be found here. 
</p> 

<p>
	Another ever-growing discussion of web accessibility that needs to be featured more: making a commitment to providing multilingual websites, therefore attracting more users and the larger audience. Globalization is and will continue to have a larger vast of influence on internet users.
</p> 

<p>
	To create more business and foot traffic to your website, make the first effort by offering diverse languages for diverse users. 
</p> 

<p>
	The U.S. technology industry is not as inclusive as it should be of diverse language speakers. In order to stay progressive, more of our websites need to scale to meet a larger and diverse global audience.
</p> 

<p>
	People with disabilities tend to be kept hidden in our society and popular culture. Our larger global audience of speakers tend to be forgotten about as well. As we strive to improve diversity in internet culture - we must be sure to include everyone, including people with disabilities. 
</p> 

</div>


	</div>
</div> <!-- closing index-content -->
</div> <!-- closing sidebar wrapper -->
</div> <!-- closing div content-wrapper -->

web-accessibility/app/views/capstone/translate.html.erb
<%= stylesheet_link_tag "translate" %>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<%= link_to "Return Home", capstone_path %> <br>
<%= link_to "CSS Demo", capstone_css_path %>

<div id="wrapper">
       
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span class="navbar-brand"> Web Accessibility </span>
            </div>
				</nav>
		</div>		

	<div id="content-wrapper">

	<div id="sidebar-wrapper" class="col-md-offset-2">

		<div class="collapse navbar-collapse navbar-ex1-collapse fixed">

			<ul class="nav navbar-nav side-nav border down">
			
				<li>
					<%= link_to "Home", capstone_path %>
				</li>

				<li>
					<%= link_to "Twilio Demo", capstone_twilio_path %>
				</li>

				<li>
					<%= link_to "Speech-to-Text Email", capstone_email_path %>
				</li>

				<li>
					<%= link_to "Google Translate", capstone_translate_path %>
				</li>

				<li>
					<%= link_to "ARIA & CSS", capstone_css_path %>
				</li>
	
			</ul>
		</div> <!-- closes sidebar-wrapper -->

	<div class="col-md-12 translate-content-down">
		<div id="translation-content">

					<div id="google_translate_element"></div>
					<script type="text/javascript">
						function googleTranslateElementInit() {
  					new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages: 'es,zh-CN,zh-TW', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
						}
					</script>
					<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

		<h1 class="translate-title"> 
			<i class="fa fa-bookmark index-bookmark" aria-hidden="true"> </i>
				Google Translate Demo </h1>
			
			<hr class="translate-hr col-md-7">

			<%= image_tag("food-vegetables-meal-kitchen.jpg", :class => "veggie-img") %>

		<!-- <div> -->
			<p class="demo-description col-md-10"> This demo was created to showcase how to change your site's language. This demo shows how to change the main language english to a choice of spanish or chinese. This site will have all the same design and functionality.

<span class="translate-to-email-tag"> 
  <p class="p-twilio-left col-md-8">

    <i class="fa fa-long-arrow-left" aria-hidden="true"></i>

    Go to <%= link_to "Email Demo",
    capstone_twilio_path, {:class => "index-project-link"} %>
  </p>

 <!--  <p class="p-translate-right col-md-8 right"> -->

	<span class="slight-right">
  Go to <%= link_to "ARIA & CSS Demo",
  capstone_css_path, {:class => "index-project-link"} %>
    
    <i class="fa fa-long-arrow-right" aria-hidden="true"> </i>
  <!-- </p> -->
</span>
</p>

</p>

</div> <!-- closes row		 -->
</div> <!-- closes the columns -->

<div class="further-reading google-translate-tutorial col-md-8">

<span class="index-further-reading"> 
		Further Reading: 
</span> <br>

<span class="translation-report"> How to Incorporate the Google Translate Plug-in Into Your Website </span>

<p class="aria-move-p">
	The internet has become the prime communication hub for businesses and individuals looking for goods, services, or information. For companies looking to increase sales and to gain a competitive advantage, one of the best ways to achieve this is by creating a multilingual website. 
</p> 

<p class="aria-move-p">
	The internet originally began as an English speaking convention, and in the beginning it was dominated by English speakers and users. Having a multilingual site is one of the best ways to market your company, bringing in a new audience of users and creating new relationships.
</p> 

<p class="aria-move-p">
	Let’s say you have a website already completed, but want to add in different language selections to your site.
</p> 

<span class="aria-move-p"> 
	<strong>
		How to add the Google Translate Widget to your website: 
	</strong>
</span> <br>

<span class="aria-move-p"> 1. Visit the Google Translation Manager, sign into your Google Account (If you don’t have an account already, you can sign up for a free Google account). </span> <br>

<span class="aria-move-p"> 2. Click the ‘Add to your website now’ on the right­hand side. </span> <br>

<span class="aria-move-p"> 3. Follow the instructions on the next few pages to customize your language translator, so that you can add the languages of your choice to your website. </span> <br> 

<span class="aria-move-p"> 4. Add the Google widget code to the webpage where you’d like your translator to be. Paste and add the widget/html element. </span> <br>

<span class="aria-move-p"> Since you're most likely using a few different languages, make sure to give enough space for various word interpretations in terms of web design and layout. </span> 
	
</div>

web-accessibility/app/views/capstone/twilio.html.erb
<%= javascript_include_tag "application" %>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <div id="wrapper">

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    
                    <span class="icon-bar"></span>
                    
                    <span class="icon-bar">
                    </span>
                </button>
                <span class="navbar-brand">
                 Web Accessibility 
                 </span>
            </div>
				</nav>
		</div>		

<div id="content-wrapper" class="twilio-sidebar-down">

	<div id="sidebar-wrapper" class="col-md-offset-2">

		<div class="collapse navbar-collapse navbar-ex1-collapse fixed">
		
		<ul class="nav navbar-nav side-nav border down relative">
			
			<li>
				<%= link_to "Home", capstone_path %>
			</li>

			<li>
				<%= link_to "Twilio Demo", capstone_twilio_path %>
			</li>

			<li>
				<%= link_to "Speech-to-Text Email", capstone_email_path %>
			</li>

			<li>
				<%= link_to "Google Translate", capstone_translate_path %>
			</li>

			<li>
				<%= link_to "ARIA & CSS", capstone_css_path %>
			</li>
	
		</ul>
	</div> <!-- closes sidebar-wrapper -->

<div id="twilio-content" class="col-md-6">

	<h1 class="twilio-title">
		<i class="fa fa-bookmark index-bookmark" aria-hidden="true"> </i>
	Web Speech Twilio Demonstration</h1>
	<hr>
	<div id="status"></div>
		<p></p>

	<form action="http://localhost:3000/capstone/twilio" method="get">
  	<input name="q" id="input_field" size="70">
	</form>
	
	<button onclick="reco.toggleStartStop()" style="border: 0; background-color:transparent; text-align:center">
		<%= image_tag "mic.gif", :class => "twilio-mic" %>
	</button>


<p class="twilio-move-p col-md-8" style="margin-top:40px;">
		This application demonstrates how to use Google Web Speech API with Twilio API. It uses Google Speech Recognition Software to send as output to a mobile phone with the Twilio API. 
	</p>

	<p class="twilio-move-p col-md-8">
		This project was inspired by my appreciation for cross-platform technology. This application is being used from my laptop, however this API can be used with a browser on a laptop or mobile phone.
	</p>

	<br>

	<div class="twilio-to-index-tag col-md-8">

		<p class="p-twilio-left left">
			<i class="fa fa-long-arrow-left" aria-hidden="true"> </i>
				Go to <%= link_to "Home", capstone_path, {:class => "index-project-link"} %>
		<!-- </p> -->

		<!-- <p class="p-email-right right"> -->
			<span class="right">
			  Go to <%= link_to "Email Demo", capstone_email_path, {:class => "index-project-link"} %> 
			  
			  <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
			</span>  
		</p>

	</div>	

<div class="twilio-further-reading col-md-8">
	
	<span class="twilio-further-reading"> 
		Further Reading:
	</span> <br>

	<span class="twilio-report"> Tutorial: </span> <br>
	
	<span class="twilio-report"> Incorporating Google Web Speech Api with Twilio Communications API </span> <br>
	
	<p class="twilio-move-p">
		This tutorial explains how to use Google Web Speech API along with Twilio API. This application uses Google Speech Recognition Software to send as output to a mobile phone device with the Twilio API. 
	</p>

	<p class="twilio-move-p">
		This project was inspired by the use of technology being cross-platform. For example, this demonstration is being used from my laptop, but it can be used in a browser on a mobile phone.
	</p>

	<p class="twilio-move-p">
		Or perhaps used by a user that doesn't have a smart phone, or doesn't have a smart phone with SIRI capability. Either way, users who don't have a phone or phone capabilities can use this demo. 
	</p>

	<p class="twilio-move-p">
		This demo is made possible with Ruby on Rails, I incorporated the Google Web Speech API into my twilio.html.erb file.
	</p>

	<span><strong> Directions: </strong></span>

	<p class="twilio-move-p">
		Starting out, Google provides a helpful tutorial on how to use their speech-to-text API. I will walk you through how the code is working. You need to download the codelab files from the tutorial to see the various speech-to-text demos.
	</p>

	<p class="twilio-move-p">
		Once you have your basic code in place with HTML and JavaScript, you can style your speech-to-text API in whichever layout you choose - whether it be Bootstrap, CSS, Less, or Sass. In my application, I am using Sass and Bootstrap. The code provided also comes with a reset.css file, as well as some styling incorporated into the HTML file.
	</p>

	<p class="twilio-move-p">
		In this demo I used the provided code from codelab1solution.html into my index.html.erb file. I created three separate files using HTML, CSS, and JavaScript, as well as including images and the webspeech.js file.
	</p>

	<p class="twilio-move-p">
		Looking at the HTML code provided in the codelab1solution.html file, let's check out how this code is working:
	</p>

	<span> < form action="http://localhost:3000/capstone/twilio" method="get" >
  	< input name="q" id="input_field" size="100" >
< /form > </span>

	<p class="twilio-move-p">
		The form get method is retrieving the input named "q" from the input field. Input q is standing as our user's input. Below the previous code, you'll find the code button with the JavaScript function reco.toggleStartStop(). Styling on this button is applied with border, and transparent as the background color. The image tag "mic.gif" is acting as the button.
	</p>

	<span>
			< form action="http://google.com/search" method="get" >
  	< input name="q" id="input_field" size="100">
	</form >

< button onclick="reco.toggleStartStop()" style="border: 0; background-color:transparent" >
  	< img id="status_img" src="mic.gif" alt="Start" >
  < /button>
	</span>

	<p class="twilio-move-p"> This script tag is calling in the webspeech.js file. </p>

	<span> 
	< script src="webspeech.js">< /script> 
	</span>

	<p class="twilio-move-p">
		At the end of the html file, apply the script tag. This script file is calling the var reco, with the JavaScript function WebSpeechRecognition().
	</p>

	<p class="twilio-move-p">
		In the webspeech.js file, we see that this Javascript function is creating and returning the new WebSpeechRecognition object. 
	</p>

	<p class="twilio-move-p">
		reco.onEnd is holding a function with a boolean statement, saying if the reco.final_transcript is not equal to an empty value, submit the user's input to the form. 
	</p>

	<span>
		<script>
			var reco = new WebSpeechRecognition();
			reco.statusText('status');
			reco.statusImage('status_img');
			reco.finalResults('input_field');

			reco.onEnd = function() {
  			if (reco.final_transcript != '') {
    			input_field.form.submit();
  			}
			};
		</script>		
	</span>

	<p class="twilio-move-p">
		In my controller file in Rails, I created a file called demo_controller.rb.
	</p>

	<p class="twilio-move-p">
		When setting up my index controller, I placed my twilio API inside my index controller. 
		I set an if boolean statement, stating if the params[:q] is called from my user input's form. 
	</p>

	<p class="twilio-move-p">
		You can sign up for a free Twilio trial, and with your free account get a free phone number to send your input data to.
	</p>

	<p class="twilio-move-p">
		Since I am using Ruby on Rails, I followed the Ruby documentation on how to apply the following code to get the API working. 
	</p>

	<p class="twilio-move-p">
	<code>
		if params[:q] <br>
	</code>
	</p>

	<p>
	<code>
		require 'rubygems' # not necessary with ruby 1.9 but included for completeness <br>
		require 'twilio-ruby' <br>
	</code>
	</p>

	<p>
	<code>
		# put your credentials here <br>
		account_sid = ENV["ACCOUNT_SID"] <br>
		auth_token = ENV["AUTH_TOKEN"] <br>
	</code>
	</p>

	<p>
	<code>
		# set up a client to talk to the Twilio REST API <br>
		@client = Twilio::REST::Client.new <br>account_sid, auth_token <br>
	</code>
	</p>

	<p>
	<code>
		message = @client.account.messages.create(:body => params[:q], <br>
			:to => "+15303015894", <br>
			:from => "+15307630890") <br>
	</code>
	</p>

	<p>
	<code>
		puts message.sid <br>
	</code>
	</p>

	<p>
	<code>
		@textinformation = params[:q] <br>
	</code>
	</p>

	<p>
	<code>
		render :twilio <br>
		end <br>
	</code>	
	</p>

	<p class="aria-move-p">
		 If input is being passed into params[:q]
	</p>

	<p>
		requiring the 'rubygems', <br>
 		requiring 'twilio-ruby', <br>
		credentials are added in with your account information.
	</p>

	<p>
		account_sid = #account_sid info goes here <br>
		auth_token = #auth_token info goes here <br>
	</p>

	<p>
		Client is setup to talk to the Twilio REST API.<br>
		@client = Twilio::REST::Client.new <br>
		account_sid, auth_token <br>
	</p>

	<p>
		The message variable is calling the create message with this account:
	</p>

	<p>
		 message = @client.account.messages.create(:body => params[:q], <br>
		:to => "+18005551234", #phone number example <br>
		:from => "+18005436789") #phone number example <br>
	</p>

	<p class="twilio-move-p">
		The message is then sent out with message.sid, with the message authorized with the account_sid number information.
	</p>

	<p class="twilio-move-p">
		This is how I combined both APIs, this application translate the speech audio spoken into your computer's microphone directly as a text message to the number listed. 
	</p>

</div>






</div> <!-- closes the twilio content -->
</div><!-- closes the content wrapper -->

<!-- @text-information was here as a test to see if data was being grabbed -->

<!-- <script src="webspeech.js"></script> -->
<script>
var reco = new WebSpeechRecognition();
reco.statusText('status');
reco.statusImage('status_img');
reco.finalResults('input_field');

reco.onEnd = function() {
  if (reco.final_transcript != '') {
    input_field.form.submit();
  }
};
</script>

web-accessibility/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebAccessibility</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

web-accessibility/app/views/welcome/twilio.html.erb
<%= javascript_include_tag "application" %>

<h1> Test </h1>

<h1>Web Speech Twilio Demonstration</h1>
<div id="status">
</div>
<p></p>
<form action="http://localhost:3000/" method="get">
  <input name="q" id="input_field" size="100">
</form>
<button onclick="reco.toggleStartStop()" style="border: 0; background-color:transparent">
<%= image_tag "mic.gif" %>

  </button>

  <%= @textinformation %>

<!-- <script src="webspeech.js"></script> -->
<script>
var reco = new WebSpeechRecognition();
reco.statusText('status');
reco.statusImage('status_img');
reco.finalResults('input_field');

reco.onEnd = function() {
  if (reco.final_transcript != '') {
    input_field.form.submit();
  }
};
</script>